org: andymarch
app: okta-custom-telephony
service: okta-custom-telephony
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  logRetentionInDays: 30
  httpApi:
    authorizers:
      fixed:
        type: request
        functionName: fixedAuthorizer
        identitySource: 
          - $request.header.Authorization
  environment:
    FIXED_AUTH_SECRET: ${param:fixed-secret}
    FIRETEXT_KEY: ${param:firetext-api-key, 'not-set'}
    SENDER_ID: ${param:sender_id}
    LOG_LEVEL: ${param:log_level, 'info'}


functions:
  fixedAuthorizer:
      handler: src/authorizer/fixedsecret.authorize
  deliver:
    handler: src/telephony.handler
    events:
      - httpApi:
          path: /
          method: post
          authorizer:
            name: fixed